Repository CS2103-AY1819S1-W14-2/main, pull requests merged in 2018-09, with the labels that each got.

#42 help - change default to summarized help info
  build.gradle
  docs/ShortHelp.adoc
  docs/ShortHelpWindow.adoc
  src/main/java/seedu/address/commons/events/ui/ShowHelpRequestEvent.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: enhancement.Accessibility, status.Reviewed

#45 Update docs
  docs/DeveloperGuide.adoc
  docs/ShortHelp.adoc
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
Labels: status.Reviewed

#47 {tab} auto complete
  src/main/java/seedu/address/commons/events/ui/SuggestCommandEvent.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/systemtests/SuggestCommandSystemTest.java
Labels: enhancement.Accessibility, status.RequestReview

#48 Enhance Find feature
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ride/RideContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ride/RideContainsKeywordsPredicateTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: enhancement.Accessibility, enhancement.Data, status.Reviewed
