Repository CS2103-AY1819S1-W14-2/main, pull requests merged in 2018-10, with the labels that each got.

#51 Fix formating issues with FindCommandParser
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: status.Reviewed

#54 update jiajunteo.png
  docs/images/jiajunteo.png
Labels: status.Reviewed

#55 Undo redo tests
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: status.Reviewed

#58 V1.1
  docs/UserGuide.adoc
  docs/images/leongengsea.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: status.Reviewed

#61 Remove Unused Imports
  README.adoc
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: priority.Low, status.Reviewed

#60 Rename ListCommand as ViewAllCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/ViewAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/SuggestCommandSystemTest.java
Labels: status.Reviewed

#74 Fix coveralls badge and missing javadoc
  README.adoc
  src/main/java/seedu/address/commons/events/ui/ShowHelpRequestEvent.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: status.RequestReview

#77 Help command
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/ShowHelpRequestEvent.java
  src/main/java/seedu/address/logic/commands/AllCommandWords.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SuggestCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/exceptions/AccessibilityException.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: enhancement.Accessibility, status.RequestReview

#78 Filter Command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ThaneParkParser.java
  src/main/java/seedu/address/model/ride/AttributePredicate.java
  src/main/java/seedu/address/model/ride/Maintenance.java
  src/main/java/seedu/address/model/ride/NumericAttribute.java
  src/main/java/seedu/address/model/ride/Ride.java
  src/main/java/seedu/address/model/ride/RideContainsConditionPredicate.java
  src/main/java/seedu/address/model/ride/WaitTime.java
  src/main/java/seedu/address/model/ride/exceptions/InvalidNumericAttributeException.java
  src/test/data/XmlSerializableThaneParkTest/typicalRideThanePark.xml
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ThaneParkParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ThaneParkTest.java
  src/test/java/seedu/address/model/VersionedThaneParkTest.java
  src/test/java/seedu/address/model/ride/MaintenanceTest.java
  src/test/java/seedu/address/model/ride/RideTest.java
  src/test/java/seedu/address/model/ride/UniqueRideListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedRideTest.java
  src/test/java/seedu/address/storage/XmlSerializableThaneParkTest.java
  src/test/java/seedu/address/storage/XmlThaneParkStorageTest.java
  src/test/java/seedu/address/testutil/TypicalRides.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/RideListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: enhancement.Accessibility, status.Reviewed

#82 Enhance Find and Update Docs for Filter and Find
  _reposense/config.json
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ride/RideContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: enhancement.Accessibility, status.Reviewed

#79 History
  .gitignore
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/CommandsLogCenter.java
  src/main/java/seedu/address/commons/core/HtmlReportGenerator.java
  src/main/java/seedu/address/commons/events/ui/ShowHelpRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowHistoryRequestEvent.java
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/HistoryCommandParser.java
  src/main/java/seedu/address/logic/parser/ThaneParkParser.java
  src/main/java/seedu/address/model/logging/CommandEntry.java
  src/main/java/seedu/address/model/logging/ExecutedCommand.java
  src/main/java/seedu/address/model/ride/Maintenance.java
  src/main/java/seedu/address/model/ride/WaitTime.java
  src/main/java/seedu/address/storage/XmlAdaptedCommandEntry.java
  src/main/java/seedu/address/storage/XmlAdaptedRide.java
  src/main/java/seedu/address/storage/XmlListOfCommandEntry.java
  src/main/java/seedu/address/ui/HistoryWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HistoryWindow.fxml
  src/test/java/guitests/guihandles/HistoryWindowHandle.java
  src/test/java/seedu/address/commons/core/CommandsLogCenterTest.java
  src/test/java/seedu/address/logic/CommandHistoryTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HistoryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ThaneParkParserTest.java
  src/test/java/seedu/address/testutil/CommandEntryBuilder.java
  src/test/java/systemtests/HistoryCommandSystemTest.java
  src/test/java/systemtests/SuggestCommandSystemTest.java
Labels: enhancement.Accessibility, enhancement.Data, status.Reviewed

#75 {tab} auto complete
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/SuggestCommandSystemTest.java
Labels: enhancement.Accessibility, status.RequestReview

#84 Ui enhancement
  docs/DeveloperGuide.adoc
  docs/images/AutocompleteSuggestActivityDiagram.png
  src/main/java/seedu/address/model/ride/Ride.java
  src/main/java/seedu/address/storage/XmlAdaptedRide.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RideCard.java
  src/main/java/seedu/address/ui/RideListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RideListCard.fxml
  src/main/resources/view/RideListPanel.fxml
  src/test/data/XmlSerializableThaneParkTest/duplicateRideThanePark.xml
  src/test/data/XmlSerializableThaneParkTest/invalidRideThanePark.xml
  src/test/data/XmlSerializableThaneParkTest/typicalRideThanePark.xml
  src/test/data/XmlThaneParkStorageTest/invalidAndValidRideThanePark.xml
  src/test/data/XmlThaneParkStorageTest/invalidRideThanePark.xml
  src/test/data/XmlUtilTest/invalidRideField.xml
  src/test/data/XmlUtilTest/missingRideField.xml
  src/test/data/XmlUtilTest/tempThanePark.xml
  src/test/data/XmlUtilTest/validRide.xml
  src/test/data/XmlUtilTest/validThanePark.xml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/RideCardHandle.java
  src/test/java/guitests/guihandles/RideListPanelHandle.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/ui/RideCardTest.java
  src/test/java/seedu/address/ui/RideListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/UpdateCommandSystemTest.java
  testing7893h.xml
Labels: enhancement.Accessibility, status.RequestReview

#88 Update docs
  docs/DeveloperGuide.adoc
  docs/diagrams/AutocompleteSuggestActivityDiagram1.pptx
  docs/diagrams/AutocompleteSuggestActivityDiagram2.pptx
  docs/diagrams/AutocompleteSuggestActivityDiagram3.pptx
  docs/images/AutocompleteSuggestActivityDiagram.png
  docs/images/AutocompleteSuggestActivityDiagram1.png
  docs/images/AutocompleteSuggestActivityDiagram2.png
  docs/images/AutocompleteSuggestActivityDiagram3.png
  src/main/java/seedu/address/MainApp.java
Labels: status.Reviewed

#94 Update docs
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/team/YuPeiHenry.adoc
Labels: status.Reviewed

#96 Ui enhancement
  docs/DummySearchPage.html
  docs/images/ride.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/CommandsLogCenter.java
  src/main/java/seedu/address/commons/core/HtmlReportGenerator.java
  src/main/java/seedu/address/commons/core/StorageFileCreatingClass.java
  src/main/java/seedu/address/commons/util/CommandReportGenerator.java
  src/main/java/seedu/address/commons/util/FilePathToUrl.java
  src/main/java/seedu/address/commons/util/HtmlGenerator.java
  src/main/java/seedu/address/commons/util/RidePageGenerator.java
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/model/logging/CommandEntry.java
  src/main/java/seedu/address/model/logging/HtmlFormattable.java
  src/main/java/seedu/address/model/ride/Maintenance.java
  src/main/java/seedu/address/model/ride/Ride.java
  src/main/java/seedu/address/model/ride/WaitTime.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/HistoryWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/browser/BrowserRelatedUiPart.java
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/seedu/address/commons/core/CommandsLogCenterTest.java
  src/test/java/seedu/address/logic/CommandHistoryTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/UpdateCommandSystemTest.java
  src/test/java/systemtests/ViewCommandSystemTest.java
Labels: enhancement.Accessibility, status.RequestReview

#97 Replace quickview command with viewstatus command
  src/main/java/seedu/address/logic/commands/AllCommandWords.java
  src/main/java/seedu/address/logic/commands/QuickViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewAllCommand.java
  src/main/java/seedu/address/logic/commands/ViewStatusCommand.java
  src/main/java/seedu/address/logic/parser/ThaneParkParser.java
  src/main/java/seedu/address/logic/parser/ViewStatusCommandParser.java
  src/main/java/seedu/address/model/ride/RideStatusPredicate.java
  src/test/java/seedu/address/logic/commands/SuggestCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewStatusCommandParserTest.java
  src/test/java/seedu/address/model/ride/RideStatusPredicateTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/SuggestCommandSystemTest.java
  src/test/java/systemtests/ViewStatusCommandSystemTest.java
Labels: enhancement.Information, status.Reviewed

#101 Update docs
  docs/DeveloperGuide.adoc
  docs/ShortHelp.adoc
  docs/UserGuide.adoc
  docs/images/ThaneParkLogo.jpg
  docs/images/ViewStatusActivityDiagram.png
  docs/team/YuPeiHenry.adoc
  docs/team/jiajun.adoc
  docs/templates/_header.html.slim
  src/main/java/seedu/thanepark/logic/parser/ViewStatusCommandParser.java
Labels: status.Reviewed

#99 V1.3
  .gitignore
  _reposense/config.json
  docs/DeveloperGuide.adoc
  docs/ShortHelp.adoc
  docs/UserGuide.adoc
  docs/team/leongengsea.adoc
  src/main/java/seedu/thanepark/logic/commands/AllCommandWords.java
  src/main/java/seedu/thanepark/logic/commands/OpenCommand.java
  src/main/java/seedu/thanepark/logic/commands/ShutDownCommand.java
  src/main/java/seedu/thanepark/logic/parser/OpenCommandParser.java
  src/main/java/seedu/thanepark/logic/parser/ShutDownCommandParser.java
  src/main/java/seedu/thanepark/logic/parser/ThaneParkParser.java
  src/test/java/seedu/thanepark/logic/commands/OpenCommandTest.java
  src/test/java/seedu/thanepark/logic/commands/ShutDownCommandTest.java
  src/test/java/seedu/thanepark/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/thanepark/logic/parser/OpenCommandParserTest.java
  src/test/java/seedu/thanepark/logic/parser/ShutDownCommandParserTest.java
  src/test/java/systemtests/SuggestCommandSystemTest.java
Labels: Status.ChangeRequested

#102 Ui enhancement
  README.adoc
  docs/images/thanepark_32 - Copy.png
  docs/images/thanepark_32.png
  src/main/java/seedu/thanepark/MainApp.java
  src/main/java/seedu/thanepark/commons/core/Config.java
  src/main/java/seedu/thanepark/logic/parser/FilterCommandParser.java
  src/main/java/seedu/thanepark/model/UserPrefs.java
  src/main/java/seedu/thanepark/model/ride/Maintenance.java
  src/main/java/seedu/thanepark/model/ride/Ride.java
  src/main/java/seedu/thanepark/model/ride/WaitTime.java
  src/main/java/seedu/thanepark/model/util/SampleDataUtil.java
  src/main/java/seedu/thanepark/storage/Storage.java
  src/main/java/seedu/thanepark/storage/StorageManager.java
  src/main/java/seedu/thanepark/storage/ThaneParkStorage.java
  src/main/java/seedu/thanepark/storage/XmlAdaptedRide.java
  src/main/java/seedu/thanepark/storage/XmlThaneParkStorage.java
  src/main/java/seedu/thanepark/ui/MainWindow.java
  src/main/java/seedu/thanepark/ui/RideCard.java
  src/main/java/seedu/thanepark/ui/RideListPanel.java
  src/main/java/seedu/thanepark/ui/StatusBarFooter.java
  src/main/java/seedu/thanepark/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/thanepark_32.png
  src/main/resources/view/BlueTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RideListCard.fxml
  src/main/resources/view/RideListPanel.fxml
  src/test/java/guitests/guihandles/RideCardHandle.java
  src/test/java/guitests/guihandles/RideListPanelHandle.java
  src/test/java/seedu/thanepark/TestApp.java
  src/test/java/seedu/thanepark/commons/core/ConfigTest.java
  src/test/java/seedu/thanepark/commons/util/AppUtilTest.java
  src/test/java/seedu/thanepark/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/thanepark/model/ModelManagerTest.java
  src/test/java/seedu/thanepark/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/thanepark/storage/StorageManagerTest.java
  src/test/java/seedu/thanepark/storage/XmlAdaptedRideTest.java
  src/test/java/seedu/thanepark/storage/XmlThaneParkStorageTest.java
  src/test/java/seedu/thanepark/testutil/RideUtil.java
  src/test/java/seedu/thanepark/ui/RideCardTest.java
  src/test/java/seedu/thanepark/ui/RideListPanelTest.java
  src/test/java/seedu/thanepark/ui/testutil/GuiTestAssert.java
  src/test/java/seedu/thanepark/ui/testutil/UiPartRule.java
  src/test/java/systemtests/FilterCommandSystemTest.java
Labels: enhancement.Accessibility, status.RequestReview

#105 Fix .jar file dependencies
  .gitignore
  src/main/java/seedu/thanepark/commons/events/ui/ShowHistoryRequestEvent.java
  src/main/java/seedu/thanepark/commons/util/FilePathToUrl.java
  src/main/java/seedu/thanepark/commons/util/FileUtil.java
  src/main/java/seedu/thanepark/commons/util/HtmlGenerator.java
  src/main/java/seedu/thanepark/commons/util/RidePageGenerator.java
  src/main/java/seedu/thanepark/logic/commands/HistoryCommand.java
  src/main/java/seedu/thanepark/model/UserPrefs.java
  src/main/java/seedu/thanepark/ui/MainWindow.java
  src/main/java/seedu/thanepark/ui/browser/BrowserPanel.java
  src/main/java/seedu/thanepark/ui/browser/HelpWindow.java
  src/main/java/seedu/thanepark/ui/browser/HistoryWindow.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/seedu/thanepark/ui/BrowserPanelTest.java
  src/test/java/seedu/thanepark/ui/HelpWindowTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ThaneParkSystemTest.java
Labels: status.Reviewed, type.Bug
