Repository CS2103-AY1819S1-W14-2/main, pull requests merged in 2018-11, with the labels that each got.

#106 Update docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/startup.png
  docs/images/ui_screenshots/history-example-1.png
  docs/team/YuPeiHenry.adoc
Labels: status.Ongoing

#141 Add more sample data and resolve certain issues
  docs/UserGuide.adoc
  docs/images/ui_screenshots/filter-example-1.png
  docs/images/ui_screenshots/filter-example-2.png
  docs/images/ui_screenshots/find-example-1.png
  docs/images/ui_screenshots/find-example-2.png
  docs/images/ui_screenshots/find-example-3.png
  src/main/java/seedu/thanepark/commons/core/LogsCenter.java
  src/main/java/seedu/thanepark/logic/commands/ClearCommand.java
  src/main/java/seedu/thanepark/model/util/SampleDataUtil.java
Labels: status.Reviewed

#144 Fix bug.
  src/main/java/seedu/thanepark/logic/commands/UpdateCommand.java
Labels: status.Reviewed

#108 Update Maintenance and Docs
  docs/DeveloperGuide.adoc
  docs/ShortHelp.adoc
  docs/UserGuide.adoc
  docs/team/jiajunteo.adoc
  src/main/java/seedu/thanepark/logic/commands/QuickViewCommand.java
  src/main/java/seedu/thanepark/model/ride/Date.java
  src/main/java/seedu/thanepark/model/ride/Maintenance.java
  src/test/java/seedu/thanepark/logic/parser/ThaneParkParserTest.java
  src/test/java/seedu/thanepark/model/ride/MaintenanceTest.java
Labels: status.Reviewed

#147 Fix bug
  src/main/java/seedu/thanepark/logic/commands/UpdateCommand.java
Labels: status.Reviewed

#152 Update Name RegExp
  src/main/java/seedu/thanepark/model/ride/Name.java
  src/main/java/seedu/thanepark/model/util/SampleDataUtil.java
  src/test/java/seedu/thanepark/logic/commands/CommandTestUtil.java
  src/test/java/seedu/thanepark/logic/commands/UpdateRideDescriptorTest.java
  src/test/java/seedu/thanepark/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/thanepark/logic/parser/ParserUtilTest.java
  src/test/java/seedu/thanepark/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/thanepark/model/ThaneParkTest.java
  src/test/java/seedu/thanepark/model/ride/NameTest.java
  src/test/java/seedu/thanepark/model/ride/RideTest.java
  src/test/java/seedu/thanepark/model/ride/UniqueRideListTest.java
  src/test/java/seedu/thanepark/storage/XmlAdaptedRideTest.java
  src/test/java/seedu/thanepark/testutil/TypicalRides.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/UpdateCommandSystemTest.java
Labels: status.Reviewed

#153 Documentation
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/ShortHelp.adoc
  docs/UserGuide.adoc
  docs/images/OpenActivityDiagram.png
  docs/images/OpenSequenceDiagram.png
  docs/team/leongengsea.adoc
  src/main/java/seedu/thanepark/logic/commands/UpdateCommand.java
Labels: status.Reviewed

#159 V1.4
  docs/UserGuide.adoc
  docs/images/ui_screenshots/shutdown-example-1.png
  docs/images/ui_screenshots/shutdown-example-2.png
  docs/team/leongengsea.adoc
  src/main/java/seedu/thanepark/logic/commands/AddCommand.java
  src/main/java/seedu/thanepark/logic/commands/UpdateCommand.java
Labels: status.RequestReview
